export const movieThemes = [ { id: '3ZSf1TJZyRb0rnWYuUtdX4', name: 'Main Title' },
  { id: '2TZbQZXOuR8osP2AK8yYMN',
    name: 'Theme From Jurassic Park' },
  { id: '55xly70WJY1cx5qsoogaqs',
    name: 'Main Title/John Williams/Jaws - From The "Jaws" Soundtrack' },
  { id: '7lMb4MqMMBbApnMWHp1wC5',
    name: 'Flying - From "E.T. The Extra-Terrestrial" Soundtrack' },
  { id: '3JHiyPyEGfdFlAgbX0iS7M',
    name: 'Washington Ending / Raiders March' },
  { id: '1n8NKQRg8LVHy7oUhUgbFF', name: "Hedwig's Theme" },
  { id: '6OhvyTlsBnubNpHZz7wXuT',
    name: 'Prelude and Main Title March' },
  { id: '50csT5Qb2qOF7lHdDQ1Sbx', name: 'The Batman Theme' },
  { id: '36qn2bFfZzUwM6eIv2XOc9', name: 'Titles' },
  { id: '2IJJszwGK4NWmh3bNK6CPD',
    name:
     'The Good, The Bad and The Ugly - Il Buono, Il Brutto, Il Cattivo (Titles)' },
  { id: '569uHYIB0X324FZOBEhvit', name: 'Ghostbusters' },
  { id: '5dulYd9AKIprMoF837OTDb',
    name: 'Gonna Fly Now - Theme From "Rocky" / Remastered 2006' },
  { id: '3eiymMcHMtNeN0xKeP4WQM',
    name: 'My Heart Will Go On - Love Theme from "Titanic"' },
  { id: '1QPRmX2e3EZWskuOe5QqxM', name: 'Pink Panther Theme' },
  { id: '08QaHlMPWuO5PUxjl61bXn', name: "He's a Pirate" },
  { id: '1lJOpbGH9gjjgcIumHIBrT', name: 'Main Title Theme' },
  { id: '4Ydnu5bkQUQFZ1udb4SWRT',
    name: 'Back To The Future - Original Score/End Credits' },
  { id: '3WoSJF85H0qywD4qLp4HDd',
    name: 'Main Title (The Godfather Waltz)' },
  { id: '6jNFXIiJDOvSzFqQOk0Gt9',
    name: 'Main Title - The Terminator' },
  { id: '6fVX8mF9ZqS1V8G2ZFCbLQ', name: 'Star Trek Main Theme' },
  { id: '43YwOmGUOS3zzGvj1Feszb',
    name:
     'Also sprach Zarathustra, Op. 30, TrV 176: Prelude (Sonnenaufgang)' },
  { id: '1tzj2vY4twkNmZ5K3DUOPp',
    name: 'Theme (from "Spider Man") [Original Television Series]' },
  { id: '0U6lmEhmRVptZAX7HrauqG', name: 'Main Title' },
  { id: '4BFBElI73LzkLOBru4TKVv',
    name: 'Is She With You? - Wonder Woman Theme' },
  { id: '5SXsXjVJCWeJuf7FHvgBYR', name: 'The Avengers' },
  { id: '2stkLJ0JNcXkIRDNF3ld6c',
    name:
     `You've Got a Friend in Me - From "Toy Story"/Soundtrack Version` },
  { id: '6W7ztLBiRzBN46ZaPAcQ0F',
    name:
     `(I've Had) The Time Of My Life - From "Dirty Dancing" Soundtrack` },
  { id: '25lQDEclLoUa0dZD25VRXV', name: 'Jungle Boogie' },
  { id: '0i1DZd8BYhdOPebWdF2QLz',
    name: 'Misirlou (Alternative Take)' },
  { id: '3Y9wdXMh6sNt9fUwUqTqb7', name: 'Twisted Nerve' },
  { id: '0Rynk2V7LyLgBUjTMxvbEJ', name: 'Green Hornet' },
  { id: '6Q32Vkucx2qeuVyBd3NiFZ',
    name: 'Battle Without Honor Or Humanity' },
  { id: '3k5EGEcMzBkV6kpMnDe7jZ', name: 'Garbage Truck' },
  { id: '0fx2BkX6CYYDteR8HiLf1Y', name: 'Black Sheep' },
  { id: '6d8AnIyJ3c7vjSMFJai6vc', name: 'We Are Sex Bob-Omb' },
  { id: '1nwEaIlOEGNej38iV78SE4', name: 'Threshold' },
  { id: '2pKi1lRvXNASy7ybeQIDTy', name: 'Anyone Else But You' },
  { id: '5QACbpHAaeH9jNFTGHCExA',
    name: 'Traditional Arrangement: "Moonshine"' },
  { id: '6mb69VeCGjhabqZDaws0gP',
    name: 'Too Hot To Stop - Pt. 1' },
  { id: '5f0GKx4D82I93UcRAG38Ju', name: 'Roda' },
  { id: '6YTBfxkdGce9pLEy9jG9Jo', name: 'Mais Que Nada' },
  { id: '0Jw3cPBXlGnA6DEJrZSTI0', name: 'Soul Bossa Nova' },
  { id: '6tnADR5WJUtm6VnF6hd72q',
    name: 'Just The Two Of Us - Dr. Evil Mix' },
  { id: '3QqpuxOVpfu6myl9QNtnWj', name: 'We Luv U' },
  { id: '3IeCYkdKI55mNMl2o4vX0k', name: 'Bust A Move' },
  { id: '6vFD3c1WI1zuKoyk22dMw3', name: 'Little Things' },
  { id: '1ghlpxVfPbFH2jenrv9vVw', name: 'Duel of the Fates' },
  { id: '580Mdjn5BkDnnxf7TOJ5ur',
    name:
     'The Imperial March - From "Star Wars: The Empire Strikes Back"' },
  { id: '6QmMCtfu6uHG1TbWHe0H7G',
    name: 'Raiders March (From "Raiders of the Lost Ark")' },
  { id: '52cYivJcryreRplexrYTlC',
    name: "The Name's Bond... James Bond" },
  { id: '7swocJUCUWTCiRUAU9oerC',
    name: 'Halloween Theme - Main Title' },
  { id: '1FlxqJmoZWS2q1uRlyZVur',
    name:
     'Main Title "Somewhere in My Memory" (From "Home Alone") - Voice' },
  { id: '5wsHtmFHWntJzcN6n8ivjd', name: "Rey's Theme" },
  { id: '7iocNjLrxPHLl8njgRlv5U', name: 'Married Life' },
  { id: '6pWgRkpqVfxnj3WuIcJ7WP', name: 'Cornfield Chase' },
  { id: '644es5aYPJghtZLjM1rmSP', name: 'Concerning Hobbits' },
  { id: '1IgRTNHVwz4iFhWxSTqiUi',
    name: "Writing's On The Wall - Instrumental" },
  { id: '0NGVyXhUkqE3MRN6TmSzuG', name: 'Enterprising Young Men' },
  { id: '4Pk1KXtkFTJNKLqwHhD3Zn',
    name: 'Main Titles (Fantastic Beasts and Where to Find Them)' },
  { id: '1Vk4yRsz0iBzDiZEoFMQyv',
    name: 'Mia & Sebastian’s Theme' },
  { id: '2bonbKENtFAQQh8U4UEAu5', name: 'Engagement Party' },
  { id: '4DR5MStkWtDYf17jBUOo0V', name: 'Little Green Bag' },
  { id: '1b7LMtXCXGc2EwOIplI35z',
    name: 'Stuck In The Middle With You' },
  { id: '6S9lcjREUTU4Yv5y7oMcv2', name: 'Woo Hoo' },
  { id: '7e8njbgEj7safbzhmHwMG2',
    name: 'Django - Main Theme - English Version' },
  { id: '1I6q6nwNjNgik1Qe8Oi0Y7',
    name: 'Do You Really Want To Hurt Me' },
  { id: '1LyW3Cwi49N1l58Pf1TNKy', name: 'Somebody Kill Me' },
  { id: '0FWhGmPVxLI6jOVF0wjALa', name: "Rapper's Delight" },
  { id: '561F1zqRwGPCTMRsLsXVtL', name: 'Time in a Bottle' },
  { id: '5EOoMWIB9iK4ZpcSex9Ec7', name: 'Old Time Rock & Roll' },
  { id: '2TVxnKdb3tqe1nhQWwwZCO', name: 'Tiny Dancer' },
  { id: '0LuVpXVTaWY9Un2w9GkXjf', name: 'Mad World' },
  { id: '4S118IKPxjvc9XZWXq3Wp5', name: 'Who Is Tyler Durden?' },
  { id: '4Nh59W4GVNx9J3UBwEo4cD', name: 'Homework' },
  { id: '1EUsHRQYGhIACAGsWfTwCP', name: 'Single Serving Jack' },
  { id: '6NOId30dbtZ0rU3em9KqT9', name: 'Corporate World' },
  { id: '7kWHkynIXcKgclR200P80h', name: 'Stealing Fat' },
  { id: '3ENuM3F0mPf0njRMLBxPTH', name: 'Dirty Walk' },
  { id: '6UJ9glX2SgK7quDFHiKbcu', name: 'Doors and Distance' },
  { id: '7guz8LWGuiHSvp19OUxmbQ', name: 'America' },
  { id: '0WviwuG403gqtW6bZevBpP', name: 'Aquarius' } ]
